# ============================================================
# Supplementary geographic map
# ============================================================
#
# REQUIRED:
# 1. output/tables/Table1_country_global_WT_NWT.csv
#    generated by scripts/01_final_analysis.R
#
# 2. A country-level Latin America shapefile supplied by the user:
#    data/shapefile/LatinAmerica.shp
#
# The shapefile is intentionally not distributed in this repository.
# See data/shapefile/README.md.
#
# No individual coordinates are used.
# ============================================================

SHAPEFILE <- file.path("data", "shapefile", "LatinAmerica.shp")
COUNTRY_FIELD <- "CNTRY_NAME"

pkgs <- c("sf", "ggplot2", "dplyr", "tidyr", "scatterpie", "ggrepel")
to_install <- pkgs[!vapply(pkgs, requireNamespace, logical(1), quietly = TRUE)]
if (length(to_install) > 0) install.packages(to_install)
invisible(lapply(pkgs, library, character.only = TRUE))

counts_file <- file.path("output", "tables", "Table1_country_global_WT_NWT.csv")

if (!file.exists(counts_file)) {
  stop("Country summary not found. Run scripts/01_final_analysis.R first.")
}

if (!file.exists(SHAPEFILE)) {
  stop(
    "Shapefile not found: ", SHAPEFILE, "\n",
    "See data/shapefile/README.md."
  )
}

latin_america <- sf::st_read(SHAPEFILE, quiet = TRUE)

if (!COUNTRY_FIELD %in% names(latin_america)) {
  stop(
    "Country field '", COUNTRY_FIELD, "' was not found in the shapefile. ",
    "Edit COUNTRY_FIELD near the top of this script."
  )
}

counts <- readr::read_csv(counts_file, show_col_types = FALSE)

country_key <- tibble::tribble(
  ~country, ~shape_country,
  "Argentina", "Argentina",
  "Brazil", "Brazil",
  "Costa Rica", "Costa Rica",
  "Guatemala", "Guatemala",
  "Mexico", "Mexico",
  "Uruguay", "Uruguay"
)

counts <- counts |>
  dplyr::left_join(country_key, by = "country")

latin_america_proj <- sf::st_transform(latin_america, 8857)

study_shapes <- latin_america_proj |>
  dplyr::filter(.data[[COUNTRY_FIELD]] %in% country_key$shape_country)

names(study_shapes)[names(study_shapes) == COUNTRY_FIELD] <- "shape_country"

study_shapes <- study_shapes |>
  dplyr::left_join(counts, by = "shape_country")

country_points <- sf::st_point_on_surface(study_shapes)
coords <- sf::st_coordinates(country_points)

pie_data <- country_points |>
  sf::st_drop_geometry() |>
  dplyr::mutate(
    x = coords[, 1],
    y = coords[, 2],
    x_plot = dplyr::case_when(
      country == "Guatemala" ~ x - 110000,
      country == "Costa Rica" ~ x + 160000,
      country == "Uruguay" ~ x + 130000,
      TRUE ~ x
    ),
    y_plot = dplyr::case_when(
      country == "Guatemala" ~ y + 90000,
      country == "Costa Rica" ~ y - 70000,
      country == "Uruguay" ~ y + 80000,
      TRUE ~ y
    ),
    radius = sqrt(Total) * 30000,
    label = paste0(
      country, " (n=", Total, ")\n",
      "WT ", WT, " / NWT ", NWT
    )
  )

map_colors <- c("WT" = "#0072B2", "NWT" = "#D55E00")

p_map <- ggplot() +
  geom_sf(
    data = latin_america_proj,
    fill = "grey95",
    color = "grey65",
    linewidth = 0.25
  ) +
  geom_segment(
    data = pie_data |>
      dplyr::filter(x != x_plot | y != y_plot),
    aes(x = x, y = y, xend = x_plot, yend = y_plot),
    linewidth = 0.35
  ) +
  scatterpie::geom_scatterpie(
    data = pie_data,
    aes(x = x_plot, y = y_plot, r = radius),
    cols = c("WT", "NWT"),
    color = "grey20",
    linewidth = 0.25,
    alpha = 0.95
  ) +
  scale_fill_manual(values = map_colors, name = "Phenotype") +
  ggrepel::geom_text_repel(
    data = pie_data,
    aes(x = x_plot, y = y_plot, label = label),
    size = 3.1,
    min.segment.length = 0,
    box.padding = 0.5,
    point.padding = 0.5,
    seed = 20261005
  ) +
  coord_sf(expand = FALSE) +
  labs(
    title = "Distribution of environmental A. fumigatus isolates included in the study",
    subtitle = "Pie area is proportional to the number of isolates; NWT indicates non-wild-type to at least one azole",
    x = NULL,
    y = NULL
  ) +
  theme_void(base_size = 11) +
  theme(
    plot.title = element_text(face = "bold", size = 13),
    plot.subtitle = element_text(size = 9),
    legend.position = "bottom",
    legend.title = element_text(face = "bold")
  )

dir.create(file.path("output", "figures"), recursive = TRUE, showWarnings = FALSE)

ggsave(
  "output/figures/Supplementary_Figure_S3_map_WT_NWT.png",
  p_map, width = 9, height = 8, dpi = 600, bg = "white"
)

ggsave(
  "output/figures/Supplementary_Figure_S3_map_WT_NWT.pdf",
  p_map, width = 9, height = 8, bg = "white"
)

message("Supplementary map completed.")
